module4-task1
htmlacademy-nodejs/1434441-typoteka-3 pull request #11
Opened 2022-07-05 14:53 UTC by sorokkamst

2022-07-05 19:14 UTC, KletskovG requested changes

2022-07-05 19:14 UTC, KletskovG commented on src/service/cli/generate.js
> +const dateNowUnix = +date;
На всякий случай подсвечу, это чисто мое мнение, которое сформировалось при общении с другими, более опытными разработчиками.

Приводить один тип к  другому лучше более очевидным способом, то есть сделать не 
`+date`, а `Number(date)`

Разница тут есть только в том, что второй вариант более заметен для глаз,  и тут буквально видно, что идет преобразование, а `+date` можно каким-нибудь уставшим глазом спутать с оператором сложения


Примерно такое же мнение есть и о инкременте (`i++`), который используется вне цикла `for`. Лучше сделать более очевидную операцию  `i += 1`, которая намного легче визуально воспринимается (в цикле обычно оставляют `i++`, потому что  это уже многолетняя традиция и все в курсе того, что как пишутся циклы)`

В общем, просто хотел сказать, что если бы я писал эту строчку, то сделал бы `Number(date)`. Это ни в коем случае не ошибка и я не заставляю переделывать, просто написал для размышления :)

2022-07-05 19:14 UTC, KletskovG commented on src/service/cli/generate.js
> +  const decomposeArr = [];
А почему бы тут просто не сделать 


```js
const decomposeComments = (comments) => comments.map((comment) => ({
    id: nanoid(MAX_ID_LENGTH),
    text: comment,
  }));
```

2022-07-05 19:14 UTC, KletskovG commented on src/service/cli/generate.js
> +Array(count).fill({}).map(() => ({
Как мне кажется, тут можно избавиться о `.map`, просто код из `map` сразу передать в `.fill`

 Думаю, должно сработать

2022-07-05 19:14 UTC, KletskovG commented on src/service/cli/generate.js
> +Array(count).fill({}).map(() => ({
А еще тут не обязательно брать названия полей в кавычки, они нужны только для полей, которые называются через дефис, например, `user-role`

2022-07-05 19:14 UTC, KletskovG commented on src/service/cli/server.js
> +        // кажется этот catch никогда не сработает, но я могу ошибаться
Сработает, если случится непредвиденная ошибка в  `getMockData`, вдруг придет какой-нибудь новичок, и случайно сломает `getMockData`, тогда мы как раз будем защищены ` .catch`

2022-07-05 19:14 UTC, KletskovG commented on src/service/data-service/articlesService.js
> +    this._articles = this._articles.filter(article => article.id !== articleId);
В этой ситуации можно сделать быстрее 2 способами

1) Вариант, оставить один `filter`

```js
delete(articleId) {
   let result = null;
   this._articles = this._articles.filter((article) => {
      if (article.id === articleId) {
          result = article;
       }
       
       return article.id !== articleId;
   })
}
```

Тут не будет, по сути, лишнего цикла, скрытого в `find `


---

А есть второй варинт - с `find` и созданием нового массива, просто без удаленного элемента


```js
delete(articleId) {
   const articleIndex = this._articles.findIndex(article => article.id === articleId);

   if (articleIndex === -1) {
       return null;
   }

   this._articles = [...this._articles.slice(0, findIndex), ...this._articles.slice(findIndex + 1)];
   return this._articles[findIndex];
}
```


Тут просто создается новый массив, но без того элемента, который нужно удалить

2022-07-05 19:14 UTC, KletskovG commented on src/service/data-service/categoriesService.js
> +    const articles = this._articles.reduce((acc, article) => {
Поскольку ты работаешь в последней версии Node, ты можешь использовать самые свежие фишки

```js
findAll() {
  return [...new Set(
     this._articles.flatMap(article => article.categories)
  )]
 }
```


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

2022-07-05 19:14 UTC, KletskovG commented on src/service/data-service/commentsService.js
> +  drop(articleId, commentId) {
Как-то странно, в одном сервисе такой же метод назывался `delete`

2022-07-06 08:50 UTC, sorokkamst commented on src/service/cli/generate.js
> +Array(count).fill({}).map(() => ({
Не получится избавиться от `.map`, если прописать код внутри `.fill`, то мы получим массив одинаковых объектов. Подозреваю, что у `.fill` отсутствует метод перебора, он работает с точно переданными данными.

2022-07-10 13:13 UTC, merged